[package]
name = "framework-testing"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
framework.workspace = true
framework-client.workspace = true
framework-events.workspace = true
framework-jobs.workspace = true
framework-notifications.workspace = true
